version: "3"
services:
  api:
    restart: always
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9229:9229" # node debug
    depends_on:
      - "db"
    environment:
      NODE_ENV: "production"
      DATABASE: "mongodb://db:27017/place"
      PORT: 8000
      WSHOST: "api"
      WSPORT: 9000
      # WSURI: ":9000" # use this if you want the web client to connect directly to the ws server port
      WSURI: "/ws" # use this if you want the web client to go through a reverse proxy (which will then forward to WSPORT)
      ONLY_LISTEN_LOCAL: "false"
    # command: yarn debug # uncomment to allow remote debug
  db:
    image: mongo
    restart: always
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017
  # Useful if you want to browse mongodb via GUI
  # dbgui:
  #   image: huggingface/mongoku
  #   restart: always
  #   depends_on:
  #     - "db"
  #   ports:
  #     - 3100:3100
  #   environment:
  #     MONGOKU_DEFAULT_HOST: "mongodb://db:27017"
volumes:
  mongo-volume: